### ISSUE TITLE
Nginx helper only purging http

### ISSUE THREAD

**Issue by jazkh** [rtCamp/nginx-helper#217] opened 2019-10-22 18:21 UTC
I have recently installed nginx helper with nginx 1.17.
If i am using curl, then i am getting ssl error for https link.
If i choose second option to delete cache file and link is modified with http then it is not purging https. If link is modified with https, then it does not purge simple http. I get error that http or https is not cached.
Do i need to use seperate cache folder for both http and https?
I want to purge both http and https.

**Comment by mrrobot47** [comment] 2020-11-05 09:30
Closing as duplicate of #54

**Closed by mrrobot47** 2020-11-05 09:30 UTC
