### ISSUE TITLE
'auto' purge: unexpected behaviour when logged in via https:

### ISSUE THREAD

**Issue by czauner-privat** [rtCamp/nginx-helper#109] opened 2015-11-11 15:00 UTC
when setup according to examples, the nginx-helper purges the https://(whatever) pages _only_, and not the http://(whatever) resources when using the ngx_cache_purge module. Is somehow irritating. 

 I've currently refrained to take the $scheme out of  fastcgi_cache_key "$scheme$request_method$host$request_uri"; (want to test that for unwanted side-effects beforehand), and use the 'purge cache' option in the head-line as a work-around. Deleting files on disk may be an option too; but that limits me in setting uid of the webserver and php-fpm processes.

But to my mind a checkmark at the 'Purgin-Conditions' might be a better idea; or prging the http:// resource by default.

**Comment by mrrobot47** [comment] 2020-11-05 09:08
Closing as duplicate of #54

**Closed by mrrobot47** 2020-11-05 09:08 UTC
