### ISSUE TITLE
Since upgrading to PHP 8, I'm getting a 502 Bad Gateway when trying to purge the entire cache

### ISSUE THREAD

**Issue by jacklenox** [rtCamp/nginx-helper#255] opened 2021-04-23 11:30 UTC
I think this has coincided with me upgrading to PHP 8, but I now get a 502 Bad Gateway when I try to purge all content. I think the request is successful, but the response header seems to be causing issues. I've had a look at the NGINX logs and I'm seeing:
`upstream sent too big header while reading response header from upstream`

This in general appears to relate to buffers being too small, but I'm seeing this error even with `fastcgi_buffering off`. Although I believe response headers are always buffered. So I've also tried upping my buffers to quite silly levels, but I still see the 502.

Let me know if I can provide any further details.

**Comment by PDowney** [comment] 2022-10-07 08:11
I can confirm that this is happening on PHP 8.1 as well.

**Comment by webdados** [comment] 2022-12-14 16:06
Same here

**Comment by rzvagelsky** [comment] 2022-12-23 21:59
Getting a 502 error here as well.  Works fine to clear single page URL but on our multisite it goes straight to 502 for full purge from network on site purge from individual sites.

**Comment by rzvagelsky** [comment] 2022-12-23 22:14
Problem solved for me...it was the Query Monitor plugin.

**Comment by webdados** [comment] 2023-01-03 13:35
I've reached the Query Monitor developer and this is what I got: https://wordpress.org/support/topic/causes-nginx-helper-to-502-when-purging-cache/#post-16323119

**Comment by gagan0123** [comment] 2023-02-01 19:44
Closing the issue since that error has nothing to do with this plugin.

**Closed by gagan0123** 2023-02-01 19:44 UTC
