### ISSUE TITLE
define RT_WP_NGINX_HELPER_CACHE_PATH is Not work!

### ISSUE THREAD

**Issue by minzak** [rtCamp/nginx-helper#143] opened 2017-09-15 22:37 UTC
in wp-config.php i have:
define( 'RT_WP_NGINX_HELPER_CACHE_PATH', '/tmp/nginx/domain' );

also i trying add to enginx domain.conf
location ~ \.php$ {
 ....
 fastcgi_param RT_WP_NGINX_HELPER_CACHE_PATH /tmp/nginx/domain;
 ....
}

And when i use in nginx-helper setings to use RT_WP_NGINX_HELPER_CACHE_PATH - it is not worked!
I always got wrong defaul url in log
**http://domain/ is currently not cached (checked for file: /var/run/nginx-cache/b/30/23c350913cd631fa615f49b9a0cea30b)**

And Not like i define -  /tmp/nginx/domain.

**Comment by mitchellkrogza** [comment] 2019-02-18 13:54
I just manually modified line 88 of class-nginx-helper.php, not sure why it's not picking up the setting from wp-config.php

**Comment by mrrobot47** [comment] 2020-11-11 10:03
Unable to reproduce this issue. Closing it.
Please try and check if this constant is defined properly in `wp-config.php`.

**Closed by mrrobot47** 2020-11-11 10:03 UTC
